#This funciton compares true interaction tables
#generated by true.gene.interactions


compare.true.interactions <- function(int.table.SA, int.table.Gr, plot.result = TRUE){
	
	cols <- brewer.pal(8, "Accent")
	sa.direct.int <- length(which(int.table.SA[,3] == "1"))/nrow(int.table.SA)
	sa.no.int <- length(which(int.table.SA[,3] == "0"))/nrow(int.table.SA)
	sa.indirect.int <- length(which(as.numeric(int.table.SA[,3]) > 1))/nrow(int.table.SA)
	sa.indirect.val <- mean(as.numeric(int.table.SA[,3])[which(as.numeric(int.table.SA[,3]) > 1)])
	
	gr.direct.int <- length(which(int.table.Gr[,3] == "1"))/nrow(int.table.Gr)
	gr.no.int <- length(which(int.table.Gr[,3] == "0"))/nrow(int.table.Gr)
	gr.indirect.int <- length(which(as.numeric(int.table.Gr[,3]) > 1))/nrow(int.table.Gr)
	gr.indirect.val <- mean(as.numeric(int.table.Gr[,3])[which(as.numeric(int.table.Gr[,3]) > 1)])
	
	result.table <- rbind(c(sa.direct.int, sa.no.int, sa.indirect.int), c(gr.direct.int, gr.no.int, gr.indirect.int))
	
	rownames(result.table) <- c("SA", "Gr")
	colnames(result.table) <- c("Direct.Int", "No.Int", "Indirect.Int")
	
	
	
	if(plot.result){
		layout(matrix(c(1,2), nrow = 1), widths = c(0.6, 0.4))
		barplot(result.table, beside = TRUE, col = cols[1:2], names = c("Direct", "None", "Indirect"), ylab = "Proportion", main = "Proportion of types of interaction")
		legend("topleft", fill = cols[1:2], legend = c("SA", "Gr"))
		barplot(c(sa.indirect.val, gr.indirect.val), col = cols[1:2], names = c("SA", "Gr"), main = "Average path length of\nindirect interactions")
		}

	final.results <- list("proportions" = result.table, "mean.indirect.length" = c("SA" = sa.indirect.val, "Gr" = gr.indirect.val))
	return(result.table)	
	
}