get.predicted.genes <- function(path = ".", vote.min = 0.5){

	#========================================================================
	#read in the required files generated by generate.triage.models()
	#========================================================================
	tissue.mat.file <- list.files(path = path, "decomp", full.names = TRUE)
	if(length(tissue.mat.file) == 0){
		stop("generate.triage.models() must be run first to generate the non.decomp.mat.RData or the decomp.mat.RData in this directory.")
		}	
	tissue.mat <- readRDS(tissue.mat.file)

	prediction.mat.file <- list.files(path = path, "Prediction", full.names = TRUE)
	if(length(tissue.mat.file) == 0){
		stop("generate.triage.models() must be run first to generate the SVM.Prediction.Mat.RData in this directory.")
		}
	prediction.mat <- readRDS(prediction.mat.file)
	#========================================================================
	
	
	tissue.mat <- as.matrix(tissue.mat)
	
	tp.mat <- tissue.mat[,1:nrow(tissue.mat)]
	tn.mat <- tissue.mat[,((nrow(tissue.mat)+1):ncol(tissue.mat))]
	full.data <- cbind(tp.mat, tn.mat)
	
	num.tissue.genes <- apply(prediction.mat, 1, function(x) length(which(x > 0)))

	votes <- apply(prediction.mat, 2, function(x) length(which(x > 0))/length(x))
	
	pdf(paste0(path, "/", "Histogram.of.SVM.votes.pdf"))
	hist(votes, breaks = 100, main = "votes", ylab = "Number of Genes", xlab = "Fraction of yes votes")
	dev.off()
	
	old.genes <- colnames(tp.mat)
	cat("Number of genes originally associated with phenotype:", length(old.genes), '\n')
	
	all.genes <- colnames(full.data)
	cat("Total genes in data set:", length(all.genes), "\n")

	called.genes <- all.genes[which(votes > vote.min)]
	cat("Number of genes associated with phenotype:", length(called.genes), "\n")
	
	new.genes <- setdiff(called.genes, old.genes)
	cat("Number of new genes associated with phenotype:", length(new.genes), "\n")

	old.genes.not.called <- setdiff(old.genes, called.genes)
	cat("Number of original genes not associated with phenotype:", length(old.genes.not.called), "\n")
	
	all.genes.in.class <- unique(c(old.genes, called.genes))
	cat("Total number of genes associated with phenotype:", length(all.genes.in.class), "\n")
	
	return(all.genes.in.class)
	
	}